"""add_incident_severity_and_return_report

Revision ID: f2aa549ef632
Revises: 0001
Create Date: 2025-07-19 12:32:49.399466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2aa549ef632'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('total_incident_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_return_reports_loan_id', 'return_reports', ['loan_id'], unique=False)
    
    # Agregar columna return_report_id a incidents
    op.add_column('incidents', sa.Column('return_report_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'return_reports', ['return_report_id'], ['id'])
    
    # Cambiar el tipo de severity a enum (esto puede requerir recrear la tabla en SQLite)
    # Por ahora, vamos a mantener el tipo SmallInteger y manejar la conversión en el código
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'return_report_id')
    op.drop_index('ix_return_reports_loan_id', table_name='return_reports')
    op.drop_table('return_reports')
    # ### end Alembic commands ### 